### ISSUE TITLE
why the major version bump?

### ISSUE THREAD

**Issue by jnardone** [Marak/faker.js#1003]
is there anything documented as to why faker went from 4.x->5.x?  were there breaking changes with the previous API?

**Comment by hovoodd** [comment]
@Marak hello

**Comment by johneas10** [comment]
Looking for this also...

Could do with a changelog?

**Comment by ohcibi** [comment]
The fastest way is by looking at the commit log from 4.x to 5.x. We are currently in the process of reworking the library. We will prepare shorter changelogs as soon as we have finished what we planned for this change. Until then commit Logs should do it.

https://github.com/Marak/faker.js/compare/v4.1.0...v5.1.0

You can use any commit ref(s) for that comparison url

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jnardone** [comment]
The real problem is that existing code (for me at least) broke, with no
indication that function signatures had changed etc., and with no
documentation on how one would migrate from 4.x->5.x.

**Comment by adamgruber** [comment]
@ohcibi It doesn't seem reasonable to ask people to look over 428 commits that changed 710 files just to figure out why there was a major version bump.

>  We will prepare shorter changelogs as soon as we have finished what we planned for this change.

If this is the case, perhaps v5 was released too soon?

**Comment by ohcibi** [comment]
Sorry for being somewhat unspecific. I'll try to put things (somewhat) clearer

> @ohcibi It doesn't seem reasonable to ask people to look over 428 commits that changed 710 files just to figure out why there was a major version bump.

I agree. I was just responding to the question for a changelog. Not to deduct a reason for this bump 👹 .

The main reason for this release is to ship as much features and bugfixes that lured in PRs for quite some time now as possible. Since it is so much it was a major release.

Regarding to soon releasing there is a misunderstanding. "what weve planned for that change" refers to the library reworks that are planned for the next releases. To list some of the biggest: esmodules, maybe(!!) typescript, allow tree shaking, deprecate obsolete helper functions.

The stuff that made up 4->5 is listed in the commit logs. Its a huge number of files and commits and *in the future* we try to keep it smaller if possible. If any it was released to late.

Currently we are still working through the numerous PRs and merge in as many useful features and bugfixes as possible.

**Comment by Marak** [comment]
If anyone was depending on `v4` for production and wants to update to `v5`, they will have to install `v5` and see what changed. Generally it should be an easy experience to update. We try not to include any radical or obtuse changes.

We did have a discussion going for about 8 months in regards to what changed in `v5`, see: https://github.com/Marak/faker.js/issues/692

As always, priority goes to those who sponsor on https://opencollective.com/fakerjs

We have a `CHANGELOG` file, it would be AMAZING if someone could accurately update and maintain it. 
_______
**New API Methods**

Added faker.date.soon https://github.com/Marak/faker.js/pull/487

Added aba routing number https://github.com/Marak/faker.js/pull/423

Added method `faker.random.float`  https://github.com/Marak/faker.js/pull/530

Added `addess.nearbyGPSCoordinate` method https://github.com/Marak/faker.js/pull/378

Added `commerce.creditCardNumber` https://github.com/Marak/faker.js/pull/382

Added `git` faker module https://github.com/Marak/faker.js/pull/662

**Locality Updates**

Added South African `za` Locale https://github.com/Marak/faker.js/pull/517

Added `nl_BE` locale https://github.com/Marak/faker.js/pull/529/

Added `fa` locality https://github.com/Marak/faker.js/pull/391

Added `ro` locality https://github.com/Marak/faker.js/pull/327

Added `ar` locality ( partial ) https://github.com/Marak/faker.js/pull/505

Added `pt_PT` locality https://github.com/Marak/faker.js/pull/714

Updated to 500 US Census names for `en` locality https://github.com/Marak/faker.js/pull/360

Added a few female names ( `sv` locale ) https://github.com/Marak/faker.js/pull/397

Wrong cell phone format for `pl` locale https://github.com/Marak/faker.js/pull/655

Added `address.zipCodeByState` method https://github.com/Marak/faker.js/pull/600

Added `ru` locale hacker directory https://github.com/Marak/faker.js/pull/476

**API Changes**

`random.alphaNumeric` now accepts count as a argument https://github.com/Marak/faker.js/pull/363


**API Fixes**

`internet.userAgent` missing random seed https://github.com/Marak/faker.js/issues/521

`commerce.price` can no longer default to 0 https://github.com/Marak/faker.js/pull/446

Generation of float numbers  https://github.com/Marak/faker.js/issues/401 https://github.com/Marak/faker.js/issues/478

Added an explict `faker.setLocale` method to resolve ES6 import issue https://github.com/Marak/faker.js/pull/488

`this` missing in password generator https://github.com/Marak/faker.js/pull/386  

**Distribution**

Update bundled jquery for demo https://github.com/Marak/faker.js/issues/489

**Comment by MrChocolatine** [comment]
I was about to create an issue for something different, regarding `faker.dataType`, with in mind:
- why is there no changelog / why is the changelog file not updated
- would you agree to create release notes for each version?

Because I came across this change, by surprise, when working on my project and seeing the `console.log()`... I was lucky.

Reading the list of commits can be... Adventurous sometimes.

> We have a CHANGELOG file, it would be AMAZING if someone could accurately update and maintain it.

As things stand it seems quite difficult to follow the PRs / the list of commits.

Some ideas to streamline all of that:

- Having a file `/.github/PULL_REQUEST_TEMPLATE.md` to force contributors to detail their changes in a unique format.

- You could use a tool (like [`release-it`](https://github.com/release-it/release-it)?) to facilitate your deployments and the creation of release notes.

**Comment by Marak** [comment]
Sounds good @MrChocolatine 

We look forward to your contributions.
