### ISSUE TITLE
Invalid Zip codes for French

### ISSUE THREAD

**Issue by komfushee** [Marak/faker.js#161]
There is an issue with the French Zip codes, sometimes it returns a US zip-code ( like 73685-9069). 

The French codes are only formated on 5 digits: https://en.wikipedia.org/wiki/Postal_codes_in_France

**Comment by Marak** [comment]
Good catch! Will accept pull request to fix this.

**Comment by komfushee** [comment]
In fact, I tried again with your demo, and there are some other values that did not match compared to the locales/fr.js : no street_prefix like "rue, avenue, place", and wrong values for : "City, State Zip".

**Comment by Marak** [comment]
The online demo is a web app built using Faker, it's not going to give you a 1:1 experience of the entire library. Take the time to look into it and you will understand.

**Comment by Marak** [comment]
Will accept pull request to fix. Thanks.

**Comment by tkoomzaaskz** [comment]
@komfushee could you please provide a PR for this?

**Comment by portse** [comment]
Although, some locales lack the proper zip/postal formats, this can also be achieved now by specifying the zipCode format explicitly like:

`faker.address.zipCode("#####");`

**Comment by Marak** [comment]
@komfushee 

Thanks for taking the time to quickly look at the faker demo. Try to understand faker supports over 30 localities and the simple demo web page isn't designed to drill into each one.

If you look at what the `faker` API actually supports, you will find all the data and methods you require. 

https://github.com/Marak/faker.js/blob/master/lib/locales/fr/address/street_prefix.js
https://github.com/Marak/faker.js/blob/master/lib/locales/fr/address/street_suffix.js

Closing since @portse seems to have resolved this.
