### ISSUE TITLE
How to fake mongodb ObjectId data?

### ISSUE THREAD

**Issue by chenweiyj** [Marak/faker.js#197]
I am testing my restful apis which use mongodb and express.js. I want to generate some data for my test database in the before hook. However, I cannot find how to generate fake data for ObjectId reference field in the mongodb document. 

Or is there any other best practice to test restful apis? Thank you.

**Comment by tkoomzaaskz** [comment]
From what I can see, [mongoDB:ObjectId](http://docs.mongodb.org/manual/reference/object-id/) is a 12-byte BSON type, constructed using:

a 4-byte value representing the seconds since the Unix epoch,
a 3-byte machine identifier,
a 2-byte process id, and
a 3-byte counter, starting with a random value.

The `ObjectId` has its own logic, which would need a little bit of time to implement, but if you want to generate 12-byte **dumb** hex hash, you could write your own function. There are two existing functions that might be interesting in this case:
 * https://github.com/Marak/faker.js/blob/master/lib/random.js#L56-L65
 * https://github.com/Marak/faker.js/blob/master/lib/helpers.js#L21-L37

**Comment by tkoomzaaskz** [comment]
@chenweiyj would you try to implement this and creates a Przy?

**Comment by codebien** [comment]
Are you using mongoose? If yes, try this:

```javascript
var id = require('mongoose').Types.ObjectId();
```

**Comment by chenweiyj** [comment]
@codebien Thank you, this solves my problem.

**Comment by amanfrinati** [comment]
> Are you using mongoose? If yes, try this:
> 
> ```js
> var id = require('mongoose').Types.ObjectId();
> ```

I don't like this solution because I have to `require(mongoose)` every times I need a new ObjectId in my tests.
```js
function mongoObjectId() {
  const timestamp = ((new Date().getTime() / 1000) | 0).toString(16);
  return (
    timestamp +
    'xxxxxxxxxxxxxxxx'
      .replace(/[x]/g, function () {
        return ((Math.random() * 16) | 0).toString(16);
      })
      .toLowerCase()
  );
}
```

from [https://gist.github.com/solenoid/1372386](https://gist.github.com/solenoid/1372386)
