### ISSUE TITLE
locales files too big, split into separate modules

### ISSUE THREAD

**Issue by ducin** [Marak/faker.js#203]
It is difficult for me to scan over a js file that has more than 1000 lines of code. I was thinking about exploding a locale .js file into a directory where each section is a different file, being loaded over commonjs require. This would be handled by  both node.js and browserify. The advantage is to make the sources more modular and readable.

And probably easier to make a fallback if only a given locale section is not provided. What do you think of this? This could be done in parts - each locale is independent afterall.

**Comment by Marak** [comment]
That seems like a good idea.

If you can do this correctly in a reasonable amount of time, please feel free. If not, I can take the time to perform this task.

You should the ability to assign users to github issues. Feel free to assign you or myself.

**Comment by tkoomzaaskz** [comment]
@Marak I've made a proof of concept, done with my mother tongue.In this pull request I've submitted only the source changes, i.e. I haven't rebuilt the entire project because it ends up with merge conflicts. Anyway, I've built it locally and tried it in both node.js and the browser and everything works fine.

All I've done is just splitting files and loading them via commonJS `require`. That's all. node.js module loading remain the same. Bundling for the browser is handled by browserify the same way it was until now.

Please let me know if you accept the change. If so, I'll do the same with the rest of the languages.

PS some of the issues are related to locales and it's difficult to spot them, when my browser or IDE hangs for a while, while having to parse and color ~10000 lines of code (and that's how locales look currently). So I hope this will help us to maintain faker.

**Comment by kovpack** [comment]
This is really good idea. I'm preparing Ukrainian locale now and will use this approach, because it is really good and clean.

**Comment by Marak** [comment]
If anyone is looking for a work-around, the current best option is to simply comment out the require statements for the locals you don't intend on using, and then re-building the library using gulp.

Not a very hard process. If anyone wants to write documentation for this, that would be great.

**Comment by Marak** [comment]
Okay. I can make a migration script to split all existing locales into folders and separate files.

You don't want to be doing this by hand. It's better to require all locales, then use `mkdirp` and `fs` modules with a little meta-programming via string concatenation to create all new modules.

I'll probably push this back until the next release, not the current release being prepared. If anyone wants to make this migration script in the mean-time, please do.

**Comment by Marak** [comment]
I've gone ahead and split all locale data into separate modules. Used a migration script to do it, so hopefully there are no errors in the data.

Feel free to review. Will try to push out the upcoming release this week.
