### ISSUE TITLE
[discussion] [feature request] [help needed] Generating fake IBAN and BIC

### ISSUE THREAD

**Issue by hellboy81** [Marak/faker.js#260]
I need code to generate fake fake IBAN and BIC in international format

**Comment by Mardaneus86** [comment]
I can't really find an algorithm to generate valid IBAN numbers on the fly. Most of the generators out there are available as a SaaS-service. Reverse engineering the IBAN validation process would be an option I guess. I just found this library that seems to do a good job at IBAN validation: https://github.com/arhs/iban.js (thanks goes to @arhs)

Specifications for IBAN are available at https://en.wikipedia.org/wiki/International_Bank_Account_Number#IBAN_formats_by_country for each country.

You would need to create a list of country codes and national bank codes per country. Then create random valid "normal" account numbers (faker.finance.account does not create valid numbers, since the account numbers have different validity characteristics per country). 

Looks like this feature is going to be quite a challenge if it's accepted.

**Comment by Marak** [comment]
Looks like a pretty easy feature to add.

You would need to import the format data from wikipedia and create a method which returned the account formatter based on country.

Seems like not a very difficult task, just one that will require a bit of copy / pasting.

**Comment by hellboy81** [comment]
May be [this can be helpful](http://toms-cafe.de/iban/iban.html)

See section  *Download*

Here you can download two versions of the IBAN program:

    `iban.js` - the JavaScript version used on this web site and
    `iban.py` - a Python terminal program.

**Comment by Marak** [comment]
Yeah, google reveals many results.

https://github.com/eriksalhus/js-iban-calculator/blob/master/src/main/js/modules/model/iban.js

**Comment by Mardaneus86** [comment]
Hm, looks like I've searched for the wrong thing :smile:. Good resources to base a solution on!

**Comment by CoDEmanX** [comment]
I got some code to generate valid IBANs, but they don't necessarily look like typical IBAN numbers, which usually contain a lot of zeros and some other patterns - is that a problem?

**Comment by Marak** [comment]
@CoDEmanX - What is wrong with the other implementations listed?

**Comment by CoDEmanX** [comment]
They are validators not generators if I'm not mistaken. The one you referred to is capable of calculating the checksum, but doesn't generate bank codes and account numbers, and the code is terribly inefficient. Also, no one bothered to write an actual generator so far for this project.

**Comment by CoDEmanX** [comment]
PR is here: #286 
Doesn't make sense to put the required data in locale files, because it makes it overly complicated, languages and countries are different things and for there are no locales so far for most of the countries' languages used in IBANs and BICs.

**Comment by Marak** [comment]
Merged with #286 

Closing.
