### ISSUE TITLE
I can't find package "practicalmeteor:faker" in Meteor JS.

### ISSUE THREAD

**Issue by thearabbit** [Marak/faker.js#265]
I can't find package `practicalmeteor:faker` in `Meteor JS`.

**Comment by Marak** [comment]
I have no clue. 

I don't use Meteor.

Maybe someone here can help.

**Comment by thearabbit** [comment]
Because I see it on this readme.

**Comment by Marak** [comment]
Ping @rbabayoff

**Comment by aaronjudd** [comment]
The `practicalmeteor:faker` package looks out of date, and isn't published to atmosphere anymore.

Suggest using:
```
meteor add digilord:faker
```
(server only)

**Comment by thearabbit** [comment]
Thank, should be update on `readme`.

**Comment by rbabayoff** [comment]
Guys, I apologize. I missed this thread. I never actually published the faker package to meteor after my PR was merged, since it was merged half a year later and during that time a new meteor community effort was made to autopublish npm packages and other libraries to meteor, every time a release tag is created in the library's repo. I suggested this in my faker PR [here](https://github.com/Marak/faker.js/pull/147). I'm also currently not using faker (but will be using it soon again), so I suggest somebody else that is using meteor to pick this up. Here are the instructions:

https://autopublish.meteor.com/howitworks

@thearabbit , I can create a new PR to update to your latest version, and publish to meteor as practicalmeteor:faker, if you don't want to update the README. Won't take me long.

**Comment by rbabayoff** [comment]
I published practicalmeteor:faker to meteor. v2.1.1, for now. Will soon publish v3.0.1.

**Comment by rbabayoff** [comment]
Faker v3.0.1 [published](https://atmospherejs.com/practicalmeteor/faker) too, works in node.js and in the browser.

**Comment by aaronjudd** [comment]
@rbabayoff :+1:
