### ISSUE TITLE
Fake Hashes (feature request)

### ISSUE THREAD

**Issue by hongkongkiwi** [Marak/faker.js#346]
Can we add MD5 & SHA hash functions for faking?

I would like to deal with random filehashes for testing.

**Comment by hellboy81** [comment]
+inf

**Comment by Marak** [comment]
We keep getting requests for this type of data, but I still don't understand what a "fake" md5 or sha is.

The way I see is that you can require another library that will generate a real md5 or sha. I won't take in any deps that do this in faker. Too much bloat.

A good alternative might be to pre-generate sets of a lot of types of valid keys for all algorithmes. Maybe 10 or 100 per encryption type. That would be useful, and not take up much space. Would include that in faker.

**Comment by Marak** [comment]
#359

**Comment by Prinzhorn** [comment]
Wouldn't something like `random.hex(length)` work for most of these things?

md5: `random.hex(32)`
sha-N: `random.hex(N / 4)`

**Comment by zpiman** [comment]
I agree with @Prinzhorn! Since these hashes are cryptographic, they should be indistinguishable from random data. If you need real hashes of, say passwords or usernames, then you should combine faker's output with a crypto library such as https://github.com/sytelus/CryptoJS or https://github.com/brix/crypto-js. The first one in particular is Google's collection of verified crypto functions. Reimplementing them in faker again would be wasteful and redundant.

**Comment by Marak** [comment]
We added hexaDecimal method with 2562420d374ba0f09639d6813c59319ba4798b4c

Closing for now
