### ISSUE TITLE
faker.finance.amount does not randomize the digits anymore

### ISSUE THREAD

**Issue by mijamo** [Marak/faker.js#361]
Hello, I was using faker 3.0.0 and everything was working perfectly. When I updated to 3.0.1 (and same with 3.1.0), faker.finance.amount now only provides "000" as digits.

Code: 
```
faker.finance.amount(58,60,4)
faker.finance.amount(58,60,4)
faker.finance.amount(58,60,4)
faker.finance.amount(58,60,4)
```

Pre-3.0.1:
```
59.4567
60.3901
58.7192
58.8835
```
3.0.1 - 3.1.0:
```
58.0000
59.0000
58.0000
60.0000
```

I don't think this is the expected behaviour.

**Comment by luisgarciaalanis** [comment]
I am seeing the same problem on node 6.0.0

**Comment by Marak** [comment]
I'm seeing the same behavior.

Does anyone know why?

A Pull Request is welcomed.

**Comment by jreina** [comment]
As I understand the source code, faker.finance.amount is taking the output of faker.random.number and multiplying by 10^4. After which it rounds, but there is no rounding to be done since the int will always end with zero. It then divides by 10^4, which gives the original output of faker.random.number.

Working on a PR.

**Comment by Marak** [comment]
@jreina - Any updates?

I am preparing next release of `faker` and would like to fix this.

Thank you!

**Comment by jreina** [comment]
@marak I have implemented a fix, but I have yet to build/run tests. I will get it done tonight. 

Thanks!
