### ISSUE TITLE
Date faker and json-schema date-format mismatch

### ISSUE THREAD

**Issue by kristianmandrup** [Marak/faker.js#425]
Trying to use [date](https://github.com/Marak/faker.js/blob/master/lib/date.js) faker with [json-schema-faker](https://github.com/json-schema-faker/json-schema-faker)

`format: 'date-time'`

`instance.date does not conform to the "date-time" format`

`"date": "Mon Oct 24 2016 14:10:10 GMT+0200 (CEST)"`

Is there a way I can force the Date to string conversion into a compatible format?
I guess I could always extend with my own date generator?

Should be one of these [date formats](https://tools.ietf.org/html/rfc3339#section-5.8)

Please add a date `format` option, using `moment.js`

`moment().format("YYYY-MM-DDTHH:mm:ssZ")`

Thanks :)

**Comment by kristianmandrup** [comment]
See https://github.com/Marak/faker.js/pull/427

**Comment by Marak** [comment]
@kristianmandrup -

I believe this issue is related to `json-schema-faker` project, and not `faker`. `json-schema-faker` is a separate project which I do not manage.

I reviewed your PR. Taking in a new dependency `moment` seems like feature bloat and is not a core competency of what `faker` does.

If you are saying that `faker` is returning invalid Date / Time objects, please let me know where and I'll take a look.

Closing for now.
