### ISSUE TITLE
Why not use andomuser.me for fake user data?

### ISSUE THREAD

**Issue by onigetoc** [Marak/faker.js#436]
Why not use https://randomuser.me/ for fake user data?

**Comment by Marak** [comment]
@onigetoc -

Well...you should understand that the `randomuser.me` project is actually using `faker` project to generate it's data. 

Look here: https://github.com/RandomAPI/Randomapi.com/blob/master/package.json#L27

So to answer your question, `faker` is already using `faker` to generate it's fake data and since `randomuser.me` is using `faker`, `faker` is already using `randomuser.me`? I'm not that good at algebra.

Cheers! 🍻
