### ISSUE TITLE
Release v4.2.0 or v5.0.0?

### ISSUE THREAD

**Issue by j0k3r** [Marak/faker.js#583]
Latest release, v4.1.0, is from 21 Feb.
A lot of commits have been made since Februrary: https://github.com/Marak/faker.js/compare/v4.1.0...master

Lots of them fixing some bugs.
Is there any chance to make a new release to include them and avoid targetting a custom commit or the master in package.json?

:hugs:

**Comment by Marak** [comment]
Probably `v5.0.0`. I don't think any APIs have breaking changes, but it would probably be better to bump version.

It takes some work to prepare and review new release correctly.

I'll try to get to a release soon. Any help would be appreciated in reviewing changes / updating changelog / updating documentation / etc.

**Comment by nemanjan00** [comment]
Any news on this?

**Comment by Marak** [comment]
Honestly, I currently have little to no motivation right now to currently be working on new releases for `faker.js`. I started faker as an academic exercise and not for any business reasons. It's always been something I've worked on because I enjoyed working on it.

Recently, I've had little to no joy working on this or any other of my free JavaScript / Node.js projects.

I'm really not happy working in a community where we have people in "leadership" roles abusing and harassing other community members due to their race, gender, religion, or political views while hiding behind a "Code of Conduct" which is selectively enforced and retroactively updated in order to protect said harassers. I've recently switched my Twitter account to private and have decided to no longer participate in any public events. The "Code of Conduct" is suppose to create an inclusive harassment free environment and I feel both excluded and harassed.

I'm still really not happy with what happened with Rod Vagg being pushed out of a leadership position either.

Consider this a hiatus. Feel free to work on your own forks or figure out someone qualified who I can grant administrative rights. Once Ashley Williams is no longer a member of the Node.js board I'll reconsider my position.

Here are the users which I recommend avoiding as they are serial harassers who are harming the community:

 - @nodebotanist
 - @rachelnicole
 - @ashleygwilliams
 - @zkat
 - @fivetanley

**Comment by nemanjan00** [comment]
Why do you care about them? Just do what you enjoy... 

I did not even know there was Node.JS community. 

I am not asking you anything except to bump version and run npm publish...

**Comment by nemanjan00** [comment]
If you ask me, f*ck them right in the pus*y.

**Comment by Marak** [comment]
New `v5.0.0` release is pending.

Please add any comments to: https://github.com/Marak/faker.js/issues/692
