### ISSUE TITLE
[Feature request] Add configurable format to date methods

### ISSUE THREAD

**Issue by Mpreyzner** [Marak/faker.js#601]
I'm using faker.js in PAW (https://paw.cloud/) using Faker.js plugin (https://paw.cloud/extensions/FakerJsDynamicValue).
I use generated dynamic dates to test APIs and some of them require specific date format and that format is not faker.js default. I have to influence over faker.js date formatting, so it is in this case unusable.

It would be great if it was possible to add second optional argument with format to date methods.
Example:
`faker.date.future(2, 'Y-m-d H:i:s')`

**Comment by HansCronau** [comment]
Faker appears to return standard JavaScript Date objects.
You could use your favourite date formatting library (for example Moment.js) to format the date to your liking.
If you (temporarily) need to store the date as a string, check out Data methods including toString(), toUTCString(), and toISOString().
Hopefully this makes faker usable for you again.

I'm not sure if it's interesting for faker to include date formatting in the future, because specialised libraries will (hopefully) always be more powerful and not that hard to include.

**Comment by JefferyHus** [comment]
`faker.date.past().toLocaleString()` will work for you

**Comment by Mpreyzner** [comment]
@JefferyHus I needed specific format for that case and integrating faker with other libs in paw is non trivial.
