### ISSUE TITLE
Jquery vulnerability in locale 

### ISSUE THREAD

**Issue by Arunkumarvelu** [Marak/faker.js#825]
someone pls help me on this to fix this
<img width="959" alt="Screen Shot 2019-09-12 at 7 28 11 PM" src="https://user-images.githubusercontent.com/10397449/64790402-ac5a0400-d593-11e9-9266-8a1dd46879f1.png">

**Comment by samir-araujo** [comment]
Hello, @Arunkumarvelu 

It would be good if you provide more information of what you're trying to achieve so we can help you with this matter.

But for what I could figure out from your screenshot is that retire-js is complaining about a dependency of another dependency of a build tool that uses a deprecated version of jQuery.

Since its just a dependency of something we can't control and its only used for the build, its not a problem that needs to be addressed.

Faker by itself does not use jQuery at all, as you can see in `package.json`

**Comment by mastermatt** [comment]
This is related to https://github.com/Marak/faker.js/issues/542. Faker was accidentally published to NPM with the directory `locale/.publish` which has an old version of jQuery siting in it. The good news is that the jQuery in this dir is never executed when using Faker.
