### ISSUE TITLE
Is this still maintaned ?

### ISSUE THREAD

**Issue by ardyfeb** [Marak/faker.js#906]

**Comment by Marak** [comment]
Yes. It's just been hard to get the thing moving forward. We've got a couple of volunteers who have contacted me and I'd like to add multiple contributors with maintainer privileges.

I'd really prefer if we could get at least one corporate backed developer to have admin privileges so we have some additional accountability for releases. Microsoft would be good.

**Comment by ardyfeb** [comment]
Sounds good, but many awesome pull request are not merged. You dont need contributor with microsoft class developer, there many developers can take this job

**Comment by Marak** [comment]
> Sounds good, but many awesome pull request are not merged and published. You dont need contributor with microsoft class developer, there many developers can take this job

Well, I would prefer to not have to wake up to 1,000 emails due to a bad merge either.

**Comment by RobertLowe** [comment]
Yea, it would great to see the npm module updated and the docs updated. How has been getting contributors, have any corporations reached out?

**Comment by Marak** [comment]
> have any corporations reached out?

No.

**Comment by Marak** [comment]
Starting May 18th I've freed ten hours a week from my regular work to help push faker.js forward. In other words, I will be taking a pay cut in order to maintain faker.

It would be really great if any corporate or company backed developers are able to get their managers to give them at least four hours a week to contribute to faker as project maintainers.

I do have Github Sponsorship setup here as well if people actually want to pay me (lol). I know it's easy to think I can just start adding any developer as a maintainer, but it's not that easy. The project has too many downloads to give maintainer rights to a person without accountability.

**Comment by RobertLowe** [comment]
Thanks @Marak 10 hours a week is huge! We owe you many thanks. I've tried promoting inside my networks, has anyone contacted you recently. It may take a few days to get the word around. I'll talk to my company about offering some assistance. Totally agree about accountability. Thanks again!

**Comment by clytras** [comment]
> Well, I would prefer to not have to wake up to 1,000 emails due to a bad merge either.

Thank you so much for your time and effort maintaining this valuable library.

Regarding things breaking, that's what tests are for, to guaranty things working and backward compatibility after pushing updates. I'm not aware of the test coverage situation though and yes, proper testing requires time as well.

Thank you again!
