### ISSUE TITLE
IBAN for Pakistan not correct

### ISSUE THREAD

**Issue by christianbaumann** [Marak/faker.js#945]
I got this IBAN generated: `PK020OQJ0032302000765089`, which is for Pakistan.
According to the [Wikipedia article](https://en.wikipedia.org/wiki/International_Bank_Account_Number#IBAN_formats_by_country), the format for an IBAN for Pakistan is `PKkk bbbb cccc cccc cccc cccc` (which is also used like that in the [lib/iban.js](https://github.com/Marak/faker.js/blob/master/lib/iban.js)), so there should be 4 alpha chars at positions 5 to 8, which is not the case for the IBAN that faker generated.

**Comment by Moosh-be** [comment]
https://github.com/Marak/faker.js/blob/3a4bb358614c1e1f5d73f4df45c13a1a7aa013d7/lib/iban.js#L812
```
      country: "PK",

      total: 24,

      bban: [

        {

          type: "c",

          count: 4

        },

        {

          type: "n",

          count: 16

        }

      ],

      format: "PKkk bbbb cccc cccc cccc cccc"

    },
```

**Comment by Moosh-be** [comment]
Note, by reading the code I see, it's not possible to  have "Always" a PK iban.

the "locale" has no influence on that.

It's  not a bug

**Comment by christianbaumann** [comment]
Disagree.
The IBAN starts with "PK", which indicates that this is an IBAN for Pakistan.

Not talking about the set locale here at all.

**Comment by Moosh-be** [comment]
What did you disagree ? I just explain what I understand in the code.
"the locale has no influence on the iban generated"

**Comment by Rizwan52422** [comment]
is it good now ??

**Comment by Moosh-be** [comment]
> is it good now ??

cfr #950 I'v juste write tests (and now we have failing test

**Comment by christianbaumann** [comment]
> What did you disagree ? I just explain what I understand in the code.
> "the locale has no influence on the iban generated"

Excuse me, than I misunderstood what you intended to say. Apologies for that.

I was refering to
> It's not a bug
To that I don´t agree.
My reasoning: If the IBAN starts witk `PK` it indicates a pakistani IBAN. The IBAN generated starts with `PK`, but fails to follow the pattern, thus I believe it is a bug,

**Comment by Moosh-be** [comment]
Not a problem, my English, is so bad than my javascript.
Currentlty in #950 I've just try to write test for the  3 issues. 
It's work but I dislike how I dow it
- add a function to test a string containing a number  because I never found how to use the "isNumber" of chai Library.
- use a stupid loop to get a PK/GE/TR IBAN.


I go to read the code to solve them, but my solution can be poor (Dangerous for the Library)

**Comment by Moosh-be** [comment]
Not a problem, my English, is so bad than my javascript.
Currentlty in #950 I've just try to write test for the  3 issues. 
It's work but I dislike how I dow it
- add a function to test a string containing a number  because I never found how to use the "isNumber" of chai Library.
- use a stupid loop to get a PK/GE/TR IBAN.


I go to read the code to solve them, but my solution can be poor (Dangerous for the Library)

**Comment by Marak** [comment]
@Moosh-be @christianbaumann 

Thank you for your contributions!

Is it possible we can get a resolution with this and #950 

What do we need to get this complete?

Thanks again!

**Comment by Moosh-be** [comment]
@Marak @christianbaumann 
I can try but  as I'm not a good js dev, I probably need a good Review of the code. 

So I prefers branch my branch .



Ping @throskam : Here I need help :)

**Comment by Moosh-be** [comment]
@Marak @christianbaumann 
I can try but  as I'm not a good js dev, I probably need a good Review of the code. 

So I prefers branch my branch .



Ping @throskam : Here I need help :)

**Comment by Moosh-be** [comment]
I'm on holliday for 2 week, perhaps without connexion I would try but can't promise
